[program:ravisn-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ravisn/artisan queue:work --queue=campaigns,webhooks,default --sleep=1 --tries=3 --max-time=3600 --max-jobs=500 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/ravisn/storage/logs/worker.log
stopwaitsecs=3600
