[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ravisn-platform/apps/core/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=90
directory=/var/www/ravisn-platform/apps/core
autostart=true
autorestart=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-worker.log
